[package]
name = "impediment"
version = "0.0.2"
edition = "2021"

[profile.release]
opt-level = 2
lto = true
codegen-units = 1
panic = 'abort'

[dependencies]

eframe = "0.20.1"
native-dialog = "0.6.3"
num = "0.4.0"
csv = "1.1.6"
nlopt = "0.5.4"
float-pretty-print = "0.1.1"
#winit = "0.27.3"
