[package]
name = "impediment"
version = "0.0.1"
edition = "2021"

[profile.release]
opt-level = 2
lto = true
codegen-units = 1
panic = 'abort'

[dependencies]

eframe = "0.18.0"
native-dialog = "0.6.3"
num = "0.4.0"
csv = "1.1.6"
nlopt = "0.6.0"
float-pretty-print = "0.1.1"
