[package]
name = "impediment"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

eframe = "0.16.0"
native-dialog = "0.6.1"
num = "0.4.0"
csv = "1.1.6"
nlopt = "0.5.4"
